# site title
title:Blog

# user name or organization name
user:yujingwen

# issue repository
repository:blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:2#51568515ca4307531ed4ad17a78585466e41f1b

# posts per page
perpage:10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
